package Resources;

public enum ImageEnum {
    MiniMapBase,
    Base,
    MiniMapBlock2,
    MiniMapPlayer,
    MiniMapEnemy,
    MiniMapBlock1,
    Killed,
    Menu,
    Cursor,
    Logo,
    A20Texture,
    A20Turret,
    A20Ammo,
    T34_85Texture,
    T34_85Turret,
    PzKpfw_IVH_Texture,
    PzKpfw_IVH_Turret,
    PzKpfw_VIH_Tiger_Texture,
    PzKpfw_VIH_Tiger_Turret,
    TigerAmmo,
    Lvl1_bg,
    Lvl1_block1,
    Lvl1_block2,
    Lvl1_miniMap,
    Victory,
    Lose,
    A1,
    A2,
    A3,
    A4,
    A5,
    A6,
}
